###NUMPY BASICS

###CREATING A NUMPY ARRAY

In [ ]:
#creating a 1-D array through numpy on a list.

import numpy as np


list_a = [2,5,8,9]
numpy_array=np.array(list_a)
print(numpy_array)

[2 5 8 9]


In [ ]:
import numpy

In [ ]:
#code to find the dimension of defined array
 print(one_d_numpy_array.ndim)
 print(zero_d_numpy_array.ndim)


IndentationError: unexpected indent (<ipython-input-11-9de802689c1a>, line 2)

In [ ]:
arr=[[1,2,3,],[4,5,6,]]
two_d_numpy_array = np.array(arr)
print(two_d_numpy_array.ndim)

2


In [ ]:
#creating array and its attributes
a=[5,7,9,11,13]
arr=np.array(a)
arr = np.array(a)
print(arr)


[ 5  7  9 11 13]


In [ ]:
a=[[1,2,3,4],[3,5,6,7]]# creating a list

print(arr)#creating the list into numpy array
print(arr.shape)#2 row 3 column
print(arr.ndim)#dimension of array
print(arr.size)#size of array
print(arr.dtype)#data type of array


[ 5  7  9 11 13]
(5,)
1
5
int64


###numpy array indexes


In [ ]:
#changing the list in array
arr=np.array([1,2,3,4,5,6,7,8,9,])
print(arr[0])
print(arr[2]+arr[4])


1
8


In [ ]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8]])
#2d array
print(arr_2d[1,2])
print(arr_2d[0,1])


7
2


In [ ]:
arr_3d=np.array([[[1,2,3],[4,5,6],[5,6,7],[7,8,9]]]) #3d array
print(arr_3d[0,0,0])






1


In [ ]:
###Negative Indexing

###Negative indexing

###slicing in numpy_array

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9])#[start:end] #start:end:step]
print(arr[1:5:2])


[2 4]


In [ ]:
arr_2d=np.array([[2,4,6,8,11],[1,3,5,7,9]])
print(arr_2d[1,0:3])
print(arr_2d[0,1:-2])

[1 3 5]
[4 6]


In [ ]:
#create a 2d array and find its dimension and shape
=np.array([[5,10,15],[20,25,30]])
print(arr_2d.ndim)
print(arr_2d.shape)


2
(2, 3)


In [ ]:
#3.use
arr=np.zeros([2,3])
print(arr)

arrr=np.arange(0,13,3)
print(arrr)



[[0. 0. 0.]
 [0. 0. 0.]]
[ 0  3  6  9 12]


In [ ]:
#create a numpy array and print it
arr=np.array([7,14,21,28])
print(arr)

[ 7 14 21 28]


In [ ]:
arr=np.array([2,4,6,8])
res=arr*3
print(res)


[ 6 12 18 24]


In [ ]:
arr=np.array([1,3,5,7,9,11])
print(arr[2])
print(arr[1:3])

5
[3 5]


In [ ]:
#4.
import numpy as np
arr=np.array([2,4,6,8])
result=arr*3
print(result)


[ 6 12 18 24]


In [ ]:
import numpy as np
arr=np.array([1,3,5,7,9,11])
print(arr[2])
print(arr[1:4])




5
[3 5 7]


##Hands-On Practice:Pandas and Matpotlib

##Exercise 1 :Creating a Pandas Series


##Pandas series=1-D array with labels

In [ ]:


#importing pandas library
import pandas as pd

###Creating a series with.series()method function and printing the series
scores = pd.Series([67,89,12,45],index=['Aarav','Bina','Cindrella','Diana'])
print(scores)

Aarav        67
Bina         89
Cindrella    12
Diana        45
dtype: int64


###Exercise 2 : creating a Pandas Dataframe

###Dataframe is in a table format

In [ ]:
import pandas as pd

data = {
    "Name": ["A", "B", "C"],
    "Age": [2, 3, 4],
    "Score": [45, 78, 90]
}

df = pd.DataFrame(data)
print(df)


  Name  Age  Score
0    A    2     45
1    B    3     78
2    C    4     90
