###Hands on practice: Linear algebra for all

Exercise 1 : Working with scalars and vectors

In [ ]:
import numpy as np

#creating a scalar
scaler=7
print("scaler:",scaler)

#creating a vector
vector=np.array([3,5,7])
print("vector:",vector)
#scaling vector through a scaler aka.scaled vector
scaled_vector=scaler*vector
print("Scaled Vector:",scaled_vector)


scaler: 7
vector: [3 5 7]
Scaled Vector: [21 35 49]


##Exercise 2: Vector addition and subtraction

In [ ]:
vector1=np.array([2,4,7,])
vector2=np.array([5,6,8])
print(vector1+vector2)
print(vector1-vector2)



[ 7 10 15]
[-3 -2 -1]


##Exercise 3: Matrix creation and basic operations

In [ ]:
#Creating a matrix
matrix1= np.array([[2,4],[5,7]])
matrix2= np.array([[6,8],[9,11]])
print(matrix1)
print(matrix1+matrix2)#Adding matrix
print(matrix1-matrix2)#subtracting matrix

[[2 4]
 [5 7]]
[[ 8 12]
 [14 18]]


## Exercise 4:Matrix multiplication

In [ ]:
matrix1=np.array([[2,4],[5,7]])
matrix2=np.array([[6,8],[9,12]])
product=np.dot(matrix1,matrix2)
print(product)



[[ 48  64]
 [ 93 124]]


In [ ]:
matrix1=np.array([[1,1],[2,2]])#a square gareko
matrix2=np.array([[2,3],[4,5]])
product=matrix1[0,0]*matrix2[0,0]+matrix1[0,1]*matrix2[1,0]#matrix multiplixcation from scratch
print(product)
product2=matrix1[0,0]*matrix2[0,1]+matrix1[0,1]*matrix2[1,1]
print(product2)
product3=matrix1[1,0]*matrix2[0,0]+matrix1[1,1]*matrix2[1,0]
print(product3)
product4=matrix1[1,0]*matrix2[0,1]+matrix1[1,1]*matrix2[1,1]
print(product4)

product=np.dot(matrix1,matrix2)
print(product)


6
8
12
16
[[ 6  8]
 [12 16]]


##Exercise 5 :Identity Matrix and Transpose

In [ ]:
identify=np.eye(10)
print(identify)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
identify=np.eye(10)
print(identify)

[[1. 0.]
 [0. 1.]]


In [ ]:
identify=np.eye(2,dtype=int)
print(identify)

matrix1=np.array([[1,1],[2,2]])
print(matrix1.T)


[[1 0]
 [0 1]]
[[1 2]
 [1 2]]


In [ ]:
identify=np.eye(2,dtype=int)
print(identify)

matrix1=np.array([[1,1],[2,2]])
print(matrix1.T)

##Exercise 6 :Matrix inverse

In [ ]:
matrix1=np.array([[2,4],[5,7]])
print(np.linalg.inv(matrix1))

[[-1.16666667  0.66666667]
 [ 0.83333333 -0.33333333]]


In [ ]:
matrix1=np.array([[2,4],[5,7]])
inverse=np.linalg.inv(matrix1)
mat_inv=np.dot(matrix1,inverse)
print(mat_inv)

NameError: name 'np' is not defined

##create a vector[7,8,9] and multiply by a scalar of 2.Print the result

In [ ]:
import numpy as np
vector=np.array([7,8,9])
result=vector*2
print(result)



[14 16 18]


##Create two vectors [3,4] and [1,2]. Compute and print their sum and difference

In [ ]:
import numpy as np
vector=np.array([7,8,9])
result=vector*2
print(result)


[6 8]
[0 0]


## 3. Create two 2X2 matrices [[0,1],[2,3]]and [[4,5],[6,7]].Compute and print teir sum.



In [ ]:

matrix1 = np.array([[0, 1], [2, 3]])
matrix2 = np.array([[4, 5], [6, 7]])
sum_matrix = matrix1 + matrix2

print(sum_matrix)

[[ 4  6]
 [ 8 10]]


##4.Create two 2X2 matrices[[2,1],[0,3]] and [[1,2],[3,4]].Compute and print their matrix product.


In [ ]:


matrix1 = np.array([[2, 1], [0, 3]])
matrix2 = np.array([[1, 2], [3, 4]])
product = np.dot(matrix1, matrix2)

print(product)

[[ 5  8]
 [ 9 12]]


##5.Create a 2x3 matrix [[5,10,15],[20,25,30]].Compute and print its transpose and a 3X3 identity **matrix**

In [ ]:

A = np.array([[5, 10, 15], [20, 25, 30]])
transpose_A = A.T

identity_3x3 = np.identity(3)


print("Original Matrix (2x3):")
print(A)

print("\nTranspose of the Matrix (3x2):")
print(transpose_A)

print("\n3x3 Identity Matrix:")
print(identity_3x3)


Original Matrix (2x3):
[[ 5 10 15]
 [20 25 30]]

Transpose of the Matrix (3x2):
[[ 5 20]
 [10 25]
 [15 30]]

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:

matrix = np.array([[5, 10, 15], [20, 25, 30]])
transpose_matrix = matrix.T
identity_matrix = np.identity(3)
print("Original Matrix (2x3):")
print(matrix)
print("\nTranspose of the Matrix (3x2):")
print(transpose_matrix)

print("\n3x3 Identity Matrix:")
print(identity_matrix)

Original Matrix (2x3):
[[ 5 10 15]
 [20 25 30]]

Transpose of the Matrix (3x2):
[[ 5 20]
 [10 25]
 [15 30]]

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
